
parameters:
  - $ref: 'parameters.yaml#/ID'
options:
  summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
  description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
  operationId: factura_options
  tags: [ 'Factura' ]
  responses:
    '204':
      description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
      headers:
        Allow:
          $ref: 'headers.yaml#/Allow'
get:
  summary: Obtiene una factura identificada por `id`
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code | Descripción | Motivo                             |
    | ------------| ------------| -----------------------------------|
    | **200**     | Existe      | Si la factura existe          |
    | **404**     | No existe   | Si no existe la factura       |
  operationId: factura_get
  tags: [ 'Factura' ]
  responses:
    '200':
      description: Factura
      headers:
        ETag:
          $ref: 'headers.yaml#/ETag'
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Factura'
    '404':
      $ref: 'responses.yaml#/Response_404'
delete:
  summary: Elimina la factura identificada por `id`
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code      | Descripción  | Motivo                                      |
    | ---------------- | -------------| --------------------------------------------|
    | **204**          |SIN CONTENIDO | La factura existía y ha sido eliminada |
    | **404**          |NO ENCONTRADO | Si la factura no existe                |
  operationId: factura_delete
  tags: [ 'Factura' ]
  responses:
    '204':
      description: factura eliminada &lt;Cuerpo de la respuesta vacío&gt;
    '404':
      $ref: 'responses.yaml#/Response_404'
put:
  tags: [ 'Factura' ]
  summary: Modifica la factura identificada por `id`.
  description:  |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint

    | Status Code | Descripción            | Motivo                                        |
    | ------------| -----------------------| ----------------------------------------------|
    | **209**     | CONTENIDO DEVUELTO     | La factura existía y ha sido actualizada |
    | **404**     | NO ENCONTRADO          | Si la factura no existe                  |
    | **412**     | CONDICIÓN PREVIA FALLÓ | Si el Tag proporcionado no está actualizado   |
    | **422**     | ENTIDAD NO PROCESABLE  | Valor no permitido en alguno de los attributos|
  operationId: factura_put
  parameters:
    - $ref: 'parameters.yaml#/ifMatchParam'
  responses:
    '209':
      description: '`CONTENT RETURNED`: la factura ha sido actualizada'
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Factura'
    '404':
      $ref: 'responses.yaml#/Response_404'
    '412':
      $ref: 'responses.yaml#/Response_412'
    '422':
      $ref: 'responses.yaml#/Response_422'