#examples:
recambio-example:
  value:
    recambios: 
    - { "recambio": { 
        "num_serie": "ZA789000","nombre_recambio": "Bujias" , 
        "info_recambio": "Dispositivo de un motor de combustión interna donde se produce la chispa eléctrica que inflama la mezcla explosiva comprimida" , 
        "proveedor_recambio": "Norauto","garantia_recambio": "2 meses","precio_recambio": "9.96","cantidad_recambio": "12","equivalencia_recambio": "El provedor es Amazon y tienen un coste de 3.31",
        "links": {
            "parent": { "href": "https://example.com/api/v1/recambios", "rel": "recambio_post recambio_cget"},
            "self": { "href": "https://example.com/api/v1/recambios/ZA789000", "rel": "recambio_get recambio_delete recambio_put" }
        }
      } }
    links: {
      "prevPage": { "href": "https://example.com/api/v1/recambios?page=2", "rel": "prevPage" },
      "nextPage": { "href": "https://example.com/api/v1/recambios?page=4", "rel": "nextPage" }
    }

response-http-400:
  value:
    type: https://httpstatuses.com/400
    title: UNPROCESSABLE ENTITY
    status: 400
    detail: El identificador único ya existe
    instance: about:blank
response-http-404:
  value:
    type: https://httpstatuses.com/404
    title: NOT FOUND
    status: 404
    detail: El recurso solicitado no está disponible.
    instance: about:blank
response-http-409:
  value:
    type: https://httpstatuses.com/409
    title: NOT FOUND
    status: 409
    detail: El recurso no reúne las condiciones requeridas para la operación.
    instance: about:blank
response-http-412:
  value:
    type: https://httpstatuses.com/412
    title: PRECONDITION FAILED
    status: 412
    detail: El ETag proporcionado no está actualizado
    instance: about:blank
response-http-422:
  value:
    type: https://httpstatuses.com/422
    title: UNPROCESSABLE ENTITY
    status: 422
    detail: Falta alguno de los atributos obligatorios o contiene un valor no admitido
    instance: about:blank