
parameters:
  - $ref: 'parameters.yaml#/num_serie'
options:
  summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
  description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
  operationId: recambio_options
  tags: [ 'Recambio' ]
  responses:
    '204':
      description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
      headers:
        Allow:
          $ref: 'headers.yaml#/Allow'
get:
  summary: Obtiene un recambio identificado por `num_serie`
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code | Descripción | Motivo                             |
    | ------------| ------------| -----------------------------------|
    | **200**     | Existe      | Si el recambio existe               |
    | **404**     | No existe   | Si no existe el recambio            |
  operationId: recambio_get
  tags: [ 'Recambio' ]
  responses:
    '200':
      description: Recambio
      headers:
        ETag:
          $ref: 'headers.yaml#/ETag'
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Recambio'
    '404':
      $ref: 'responses.yaml#/Response_404'
delete:
  summary: Elimina el recambio identificado por `num_serie`
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code      | Descripción  | Motivo                                    |
    | ---------------- | -------------| ------------------------------------------|
    | **204**          |SIN CONTENIDO | El recambio existía y ha sido eliminada    |
    | **404**          |NO ENCONTRADO | Si el recambio no existe                   |
  operationId: recambio_delete
  tags: [ 'Recambio' ]
  responses:
    '204':
      description: Recambio eliminada &lt;Cuerpo de la respuesta vacío&gt;
    '404':
      $ref: 'responses.yaml#/Response_404'
put:
  tags: [ 'Recambio' ]
  summary: Modifica el recambio identificado por `num_serie`.
  description:  |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint

    | Status Code | Descripción            | Motivo                                        |
    | ------------| -----------------------| ----------------------------------------------|
    | **209**     | CONTENIDO DEVUELTO     | El recambio existía y ha sido actualizada      |
    | **404**     | NO ENCONTRADO          | Si el recambio no existe                       |
    | **412**     | CONDICIÓN PREVIA FALLÓ | Si el Tag proporcionado no está actualizado   |
    | **422**     | ENTIDAD NO PROCESABLE  | Valor no permitido en alguno de los attributos|
  operationId: recambio_put
  parameters:
    - $ref: 'parameters.yaml#/ifMatchParam'
  responses:
    '209':
      description: '`CONTENT RETURNED`: el recambio ha sido actualizado'
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Recambio'
    '404':
      $ref: 'responses.yaml#/Response_404'
    '412':
      $ref: 'responses.yaml#/Response_412'
    '422':
      $ref: 'responses.yaml#/Response_422'