
get:
  summary: Obtiene todos las notificaciones
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code | Descripción | Motivo                             |
    | ------------| ------------| -----------------------------------|
    | **200**     | OK          | Listado de notificaciones                |
    | **404**     | NOT FOUND   | No hay ningun notificacion              |
  operationId: notificacion_cget
  tags: [ 'Notificacion' ]
  parameters:
    - $ref: 'parameters.yaml#/pageParam'
    - $ref: 'parameters.yaml#/orderParam'
    - $ref: 'parameters.yaml#/orderingParam'
  responses:
    '200':
      description: Lista de notificacion
      headers:
        ETag:
          $ref: 'headers.yaml#/ETag'
      content:
        application/json:
          schema:
            type: object
            properties:
              Notificacion:
                description: array de notificacion
                type: array
                items:
                  $ref: 'schemas.yaml#/Notificacion'
              links:
                description: Enlaces de paginación
                readOnly: true
                type: object
                properties:
                  prevPage:
                    $ref: 'schemas.yaml#/Link'
                  nextPage:
                    $ref: 'schemas.yaml#/Link'
          examples:
            notificacion-example:
              $ref: 'examples.yaml#/notificacion-example'
    '404':
      $ref: 'responses.yaml#/Response_404'
options:
  summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
  description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
  operationId: notificacion_coptions
  tags: [ 'Notificacion' ]
  responses:
    '204':
      description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
      headers:
        Allow:
          $ref: 'headers.yaml#/Allow'
post:
  summary: Añade un nueva notificacion
  description: |
    La siguiente tabla define los códigos de estado que puede devolver este endpoint
    
    | Status Code | Descripción          | Motivo                                    |
    | ------------| ---------------------| ------------------------------------------|
    | **201**     | CREATED              | La notificacion ha sido creado                 |
    | **400**     | BAD REQUEST          | El identificador único ya existe          |
    | **422**     | UNPROCESSABLE ENTITY | Falta alguno de los atributos obligatorios|
    |             |                      | o el valor no está permitido              |
  tags: [ 'Notificacion' ]
  operationId: notificacion_post
  requestBody:
    $ref: 'requestBodies.yaml#/notificacionRB'
  responses:
    '201':
      description: Nueva notificacion creada
      headers:
        Location:
          $ref: 'headers.yaml#/Location'
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Notificacion'
    '400':
      $ref: 'responses.yaml#/Response_400'
    '422':
      $ref: 'responses.yaml#/Response_422'
