apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/kubernetes-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - mock
            - --cors
            - -h
            - 0.0.0.0
            - /aos/openapi.yaml
          image: dockerluis02/backend:latest
          name: tallermecanica-backend
          ports:
            - containerPort: 4010
          resources: {}
      restartPolicy: Always
status: {}
